title: "Distributed Systems"
remote_theme: pmarsceill/just-the-docs
color_scheme: "light"
search_enabled: true

ga_tracking: UA-156157914-2

aux_links:
  "Contribute to this Wiki on GitHub!":
    - "//github.com/DistributedSystemsWiki/wiki"

footer_content: "Copyright and related rights waived via <a href=\"https://creativecommons.org/publicdomain/zero/1.0/\">CC0</a>."

exclude: ["node_modules/", "*.gemspec", "*.gem", "Gemfile", "Gemfile.lock", "package.json", "package-lock.json",  "script/", "LICENSE.txt", "lib/", "bin/", "README.md", "Rakefile"]

markdown: kramdown

plugins:
  - jekyll-sitemap
